### ISSUE TITLE
Support newer upstream

### ISSUE THREAD

**Issue by pjeby** [uafrica/commonmark-ext#1]
Hi, I'm trying to use this extension in a project, but it requires league/commonmark 0.10 and the current version of league/commonmark is 0.17.5.  Could you update the dependency requirements to allow newer versions?  Thanks.

**Comment by dakota** [comment]
Hi @pjeby. We have not need to upgrade our commonmark version. You are welcome to submit a PR upgrading to the latest league/commonmark.

**Comment by pjeby** [comment]
Closing since this is now resolved via the 0.2.0 release
