### ISSUE TITLE
README.md example casing error

### ISSUE THREAD

**Issue by EraYaN** [uafrica/commonmark-ext#4]
In the readme:
`$env->addExtension(new \CommonmarkExt\Strikethrough\StrikethroughExtension())`
needs to be
`$env->addExtension(new \CommonMarkExt\Strikethrough\StrikethroughExtension())`

Otherwise it is broken on case-sensitive filesystems.

I thought about submitting a PR, but this is probably quicker since you can edit on the website.

**Comment by johanmeiring** [comment]
README fixed, thanks @EraYaN !
